
name: Backup From Production

on:
  workflow_dispatch:

jobs:
  trigger-and-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Azure DevOps Pipeline
        id: trigger
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/OrgName/ProjectName'
          azure-pipeline-name: 'Backup-to-Github'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_PAT }}

      - name: Wait for Azure DevOps pipeline to complete
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          ORG="OrgName"
          PROJECT="ProjectName"
          PIPELINE_NAME="Backup-to-Github"

          PIPELINE_ID=$(curl -s -u :$AZURE_DEVOPS_PAT \
            "https://dev.azure.com/$ORG/$PROJECT/_apis/pipelines?api-version=7.1-preview.1" \
            | jq -r ".value[] | select(.name==\"$PIPELINE_NAME\") | .id")

          RUN_ID=$(curl -s -u :$AZURE_DEVOPS_PAT \
            "https://dev.azure.com/$ORG/$PROJECT/_apis/pipelines/$PIPELINE_ID/runs?api-version=7.1-preview.1" \
            | jq -r '.value[0].id')

          STATUS=""
          until [ "$STATUS" = "completed" ]; do
            sleep 15
            STATUS=$(curl -s -u :$AZURE_DEVOPS_PAT \
              "https://dev.azure.com/$ORG/$PROJECT/_apis/pipelines/$PIPELINE_ID/runs/$RUN_ID?api-version=7.1-preview.1" \
              | jq -r '.state')
            echo "Pipeline state: $STATUS"
          done

          RESULT=$(curl -s -u :$AZURE_DEVOPS_PAT \
            "https://dev.azure.com/$ORG/$PROJECT/_apis/pipelines/$PIPELINE_ID/runs/$RUN_ID?api-version=7.1-preview.1" \
            | jq -r '.result')

          echo "Pipeline result: $RESULT"

          if [ "$RESULT" != "succeeded" ]; then
            exit 1
          fi
